// Generated by tools/tts.py from script.json. Do not edit.
window.TIMING = {
 "fps": 30,
 "order": [
  "s01",
  "s02",
  "s03",
  "s04",
  "s05",
  "s06",
  "s07",
  "s08",
  "s09",
  "s10",
  "s11",
  "s12",
  "s13"
 ],
 "scenes": {
  "s01": {
   "title": "Cold open",
   "offset": 0.0,
   "duration": 34.133,
   "segments": [
    {
     "id": "s01a",
     "voice": "narrator",
     "start": 1.6,
     "end": 14.156,
     "sub": "At 01:19 on 8 March 2014, a voice from the cockpit of Malaysia Airlines flight 370 spoke to air traffic control for the last time.",
     "chunks": [
      {
       "text": "At 01:19 on 8 March 2014, a voice from the cockpit of Malaysia Airlines flight 370 spoke",
       "start": 1.6,
       "end": 10.165
      },
      {
       "text": "to air traffic control for the last time.",
       "start": 10.165,
       "end": 14.606
      }
     ]
    },
    {
     "id": "s01b",
     "voice": "radio",
     "start": 14.856,
     "end": 18.026,
     "sub": "\u201cGood night. Malaysian three seven zero.\u201d",
     "chunks": [
      {
       "text": "\u201cGood night. Malaysian three seven zero.\u201d",
       "start": 14.856,
       "end": 18.476
      }
     ]
    },
    {
     "id": "s01c",
     "voice": "narrator",
     "start": 19.026,
     "end": 28.123,
     "sub": "Minutes later, it vanished from air traffic control radar. Twelve years and three seabed searches later, it has never been found.",
     "chunks": [
      {
       "text": "Minutes later, it vanished from air traffic control radar.",
       "start": 19.026,
       "end": 23.148
      },
      {
       "text": "Twelve years and three seabed searches later, it has never been found.",
       "start": 23.148,
       "end": 28.573
      }
     ]
    },
    {
     "id": "s01d",
     "voice": "narrator",
     "start": 28.723,
     "end": 31.741,
     "sub": "This is the story of what we know, and what we still don't.",
     "chunks": [
      {
       "text": "This is the story of what we know, and what we still don\u2019t.",
       "start": 28.723,
       "end": 32.341
      }
     ]
    }
   ]
  },
  "s02": {
   "title": "239 on board",
   "offset": 34.133,
   "duration": 28.467,
   "segments": [
    {
     "id": "s02a",
     "voice": "narrator",
     "start": 0.8,
     "end": 9.964,
     "sub": "Flight 370 was the overnight service from Kuala Lumpur to Beijing. On board were 227 passengers and 12 crew.",
     "chunks": [
      {
       "text": "Flight 370 was the overnight service from Kuala Lumpur to Beijing.",
       "start": 0.8,
       "end": 6.453
      },
      {
       "text": "On board were 227 passengers and 12 crew.",
       "start": 6.453,
       "end": 10.414
      }
     ]
    },
    {
     "id": "s02b",
     "voice": "narrator",
     "start": 10.464,
     "end": 18.725,
     "sub": "Most were Chinese citizens. Others came from Malaysia, Indonesia, Australia, India, France, the United States and beyond.",
     "chunks": [
      {
       "text": "Most were Chinese citizens.",
       "start": 10.464,
       "end": 12.323
      },
      {
       "text": "Others came from Malaysia, Indonesia, Australia, India, France, the United States and beyond.",
       "start": 12.323,
       "end": 19.175
      }
     ]
    },
    {
     "id": "s02c",
     "voice": "narrator",
     "start": 19.225,
     "end": 27.267,
     "sub": "Among them were a group of Chinese artists returning from an exhibition, 20 employees of a chip company, and two infants.",
     "chunks": [
      {
       "text": "Among them were a group of Chinese artists returning from an exhibition,",
       "start": 19.225,
       "end": 24.05
      },
      {
       "text": "20 employees of a chip company, and two infants.",
       "start": 24.05,
       "end": 27.867
      }
     ]
    }
   ]
  },
  "s03": {
   "title": "Departure",
   "offset": 62.6,
   "duration": 38.1,
   "segments": [
    {
     "id": "s03a",
     "voice": "narrator",
     "start": 0.6,
     "end": 16.806,
     "sub": "It took off at 00:42. The Boeing 777 was flown by Captain Zaharie Ahmad Shah, who had more than 18,000 flying hours, and First Officer Fariq Abdul Hamid, 27.",
     "chunks": [
      {
       "text": "It took off at 00:42. The Boeing 777 was flown by Captain Zaharie Ahmad Shah,",
       "start": 0.6,
       "end": 8.599
      },
      {
       "text": "who had more than 18,000 flying hours, and First Officer Fariq Abdul Hamid, 27.",
       "start": 8.599,
       "end": 17.256
      }
     ]
    },
    {
     "id": "s03b",
     "voice": "narrator",
     "start": 17.306,
     "end": 30.11,
     "sub": "The plan was routine: climb northeast over the South China Sea, hand over to Vietnamese controllers at waypoint IGARI, land in Beijing at 06:30.",
     "chunks": [
      {
       "text": "The plan was routine: climb northeast over the South China Sea, hand over",
       "start": 17.306,
       "end": 23.842
      },
      {
       "text": "to Vietnamese controllers at waypoint IGARI, land in Beijing at 06:30.",
       "start": 23.842,
       "end": 30.56
      }
     ]
    },
    {
     "id": "s03c",
     "voice": "narrator",
     "start": 30.61,
     "end": 37.106,
     "sub": "At 01:07 the aircraft sent an automatic maintenance report. It was the last one it would ever send.",
     "chunks": [
      {
       "text": "At 01:07 the aircraft sent an automatic maintenance report.",
       "start": 30.61,
       "end": 34.521
      },
      {
       "text": "It was the last one it would ever send.",
       "start": 34.521,
       "end": 37.706
      }
     ]
    }
   ]
  },
  "s04": {
   "title": "Good night",
   "offset": 100.7,
   "duration": 37.7,
   "segments": [
    {
     "id": "s04a",
     "voice": "narrator",
     "start": 0.6,
     "end": 7.757,
     "sub": "At 01:19, Kuala Lumpur told the crew to contact Ho Chi Minh City. The reply was calm and ordinary.",
     "chunks": [
      {
       "text": "At 01:19, Kuala Lumpur told the crew to contact Ho Chi Minh City.",
       "start": 0.6,
       "end": 5.396
      },
      {
       "text": "The reply was calm and ordinary.",
       "start": 5.396,
       "end": 8.207
      }
     ]
    },
    {
     "id": "s04b",
     "voice": "narrator",
     "start": 8.257,
     "end": 19.952,
     "sub": "The crew never made that call. Less than two minutes later, near IGARI, its transponder stopped transmitting. Flight 370 disappeared from civilian radar.",
     "chunks": [
      {
       "text": "The crew never made that call.",
       "start": 8.257,
       "end": 10.58
      },
      {
       "text": "Less than two minutes later, near IGARI, its transponder stopped transmitting.",
       "start": 10.58,
       "end": 16.622
      },
      {
       "text": "Flight 370 disappeared from civilian radar.",
       "start": 16.622,
       "end": 20.402
      }
     ]
    },
    {
     "id": "s04c",
     "voice": "narrator",
     "start": 20.552,
     "end": 36.706,
     "sub": "But military radar, which needs no transponder, was still watching. It saw an unidentified aircraft turn sharply back to the southwest, most likely flown by hand.",
     "chunks": [
      {
       "text": "But military radar, which needs no transponder, was still watching.",
       "start": 20.552,
       "end": 27.275
      },
      {
       "text": "It saw an unidentified aircraft turn sharply back to the southwest, most likely flown by hand.",
       "start": 27.275,
       "end": 37.306
      }
     ]
    }
   ]
  },
  "s05": {
   "title": "A ghost on military radar",
   "offset": 138.4,
   "duration": 29.867,
   "segments": [
    {
     "id": "s05a",
     "voice": "narrator",
     "start": 0.5,
     "end": 7.877,
     "sub": "The aircraft crossed back over the Malay Peninsula, passed just south of Penang Island and flew out over the Strait of Malacca.",
     "chunks": [
      {
       "text": "The aircraft crossed back over the Malay Peninsula,",
       "start": 0.5,
       "end": 3.486
      },
      {
       "text": "passed just south of Penang Island and flew out over the Strait of Malacca.",
       "start": 3.486,
       "end": 8.327
      }
     ]
    },
    {
     "id": "s05b",
     "voice": "narrator",
     "start": 8.377,
     "end": 18.281,
     "sub": "No jets were sent to intercept it. Controllers in two countries traded calls for hours. The rescue centre was not activated until 05:30.",
     "chunks": [
      {
       "text": "No jets were sent to intercept it. Controllers in two countries traded calls for hours.",
       "start": 8.377,
       "end": 14.76
      },
      {
       "text": "The rescue centre was not activated until 05:30.",
       "start": 14.76,
       "end": 18.731
      }
     ]
    },
    {
     "id": "s05c",
     "voice": "narrator",
     "start": 18.881,
     "end": 28.66,
     "sub": "At 02:22, about 200 nautical miles northwest of Penang, military radar lost it. No radar ever saw Flight 370 again.",
     "chunks": [
      {
       "text": "At 02:22, about 200 nautical miles northwest of Penang, military radar lost it.",
       "start": 18.881,
       "end": 25.657
      },
      {
       "text": "No radar ever saw Flight 370 again.",
       "start": 25.657,
       "end": 29.26
      }
     ]
    }
   ]
  },
  "s06": {
   "title": "Seven handshakes",
   "offset": 168.267,
   "duration": 44.367,
   "segments": [
    {
     "id": "s06a",
     "voice": "narrator",
     "start": 0.6,
     "end": 10.546,
     "sub": "But the aircraft left one more trace. Three minutes later, its satellite terminal logged back on to an Inmarsat satellite high above the Indian Ocean.",
     "chunks": [
      {
       "text": "But the aircraft left one more trace. Three minutes later, its satellite terminal logged back",
       "start": 0.6,
       "end": 6.808
      },
      {
       "text": "on to an Inmarsat satellite high above the Indian Ocean.",
       "start": 6.808,
       "end": 10.996
      }
     ]
    },
    {
     "id": "s06b",
     "voice": "narrator",
     "start": 11.046,
     "end": 21.708,
     "sub": "Every hour after that, a ground station in Perth exchanged a brief automatic signal with the plane: a handshake. It carried no position and no message.",
     "chunks": [
      {
       "text": "Every hour after that, a ground station",
       "start": 11.046,
       "end": 13.836
      },
      {
       "text": "in Perth exchanged a brief automatic signal with the plane: a handshake.",
       "start": 13.836,
       "end": 18.989
      },
      {
       "text": "It carried no position and no message.",
       "start": 18.989,
       "end": 22.158
      }
     ]
    },
    {
     "id": "s06c",
     "voice": "narrator",
     "start": 22.208,
     "end": 31.766,
     "sub": "But the time each signal took told investigators how far the aircraft was from the satellite. Each handshake placed the plane somewhere on a ring.",
     "chunks": [
      {
       "text": "But the time each signal took told investigators how far the aircraft was from the satellite.",
       "start": 22.208,
       "end": 28.339
      },
      {
       "text": "Each handshake placed the plane somewhere on a ring.",
       "start": 28.339,
       "end": 32.216
      }
     ]
    },
    {
     "id": "s06d",
     "voice": "narrator",
     "start": 32.266,
     "end": 38.415,
     "sub": "Tiny shifts in the signal's frequency showed it was heading south, into the southern Indian Ocean.",
     "chunks": [
      {
       "text": "Tiny shifts in the signal\u2019s frequency showed it was heading south,",
       "start": 32.266,
       "end": 36.45
      },
      {
       "text": "into the southern Indian Ocean.",
       "start": 36.45,
       "end": 38.865
      }
     ]
    },
    {
     "id": "s06e",
     "voice": "narrator",
     "start": 38.915,
     "end": 43.362,
     "sub": "Twice, the airline called the aircraft by satellite phone. No one answered.",
     "chunks": [
      {
       "text": "Twice, the airline called the aircraft by satellite phone. No one answered.",
       "start": 38.915,
       "end": 43.962
      }
     ]
    }
   ]
  },
  "s07": {
   "title": "The 7th arc",
   "offset": 212.634,
   "duration": 39.333,
   "segments": [
    {
     "id": "s07a",
     "voice": "narrator",
     "start": 0.5,
     "end": 4.992,
     "sub": "At 06:30, when it should have been landing in Beijing, the plane was still flying.",
     "chunks": [
      {
       "text": "At 06:30, when it should have been landing in Beijing, the plane was still flying.",
       "start": 0.5,
       "end": 5.442
      }
     ]
    },
    {
     "id": "s07b",
     "voice": "narrator",
     "start": 5.492,
     "end": 20.926,
     "sub": "At 08:19 it sent one last, partial handshake: most likely the engines running out of fuel and a backup power unit briefly reviving the terminal. An hour later, it did not answer.",
     "chunks": [
      {
       "text": "At 08:19 it sent one last, partial handshake: most likely the engines running out of fuel",
       "start": 5.492,
       "end": 13.253
      },
      {
       "text": "and a backup power unit briefly reviving the terminal. An hour later, it did not answer.",
       "start": 13.253,
       "end": 21.376
      }
     ]
    },
    {
     "id": "s07c",
     "voice": "narrator",
     "start": 21.526,
     "end": 27.992,
     "sub": "That final ring became known as the 7th arc. Somewhere close to it, the aircraft came down into the sea.",
     "chunks": [
      {
       "text": "That final ring became known as the 7th arc.",
       "start": 21.526,
       "end": 24.289
      },
      {
       "text": "Somewhere close to it, the aircraft came down into the sea.",
       "start": 24.289,
       "end": 28.442
      }
     ]
    },
    {
     "id": "s07d",
     "voice": "narrator",
     "start": 28.592,
     "end": 38.332,
     "sub": "On 24 March, Prime Minister Najib Razak announced that, according to the new data, Flight 370 had ended in the southern Indian Ocean.",
     "chunks": [
      {
       "text": "On 24 March, Prime Minister Najib Razak announced that, according",
       "start": 28.592,
       "end": 33.389
      },
      {
       "text": "to the new data, Flight 370 had ended in the southern Indian Ocean.",
       "start": 33.389,
       "end": 38.932
      }
     ]
    }
   ]
  },
  "s08": {
   "title": "The search",
   "offset": 251.967,
   "duration": 59.9,
   "segments": [
    {
     "id": "s08a",
     "voice": "narrator",
     "start": 0.6,
     "end": 4.295,
     "sub": "What followed became the most expensive search in aviation history.",
     "chunks": [
      {
       "text": "What followed became the most expensive search in aviation history.",
       "start": 0.6,
       "end": 4.745
      }
     ]
    },
    {
     "id": "s08b",
     "voice": "narrator",
     "start": 4.795,
     "end": 15.955,
     "sub": "Ships and aircraft from many nations combed the ocean surface. In April, an Australian ship picked up pings that seemed to come from the flight recorders. They led nowhere.",
     "chunks": [
      {
       "text": "Ships and aircraft from many nations combed the ocean surface.",
       "start": 4.795,
       "end": 8.865
      },
      {
       "text": "In April, an Australian ship picked up pings that seemed to come from the flight recorders.",
       "start": 8.865,
       "end": 14.839
      },
      {
       "text": "They led nowhere.",
       "start": 14.839,
       "end": 16.405
      }
     ]
    },
    {
     "id": "s08c",
     "voice": "narrator",
     "start": 16.455,
     "end": 29.189,
     "sub": "Then the hunt moved to the seabed: unmapped undersea mountains, water up to 6 km deep. Ships towing sonar searched more than 120,000 km\u00b2.",
     "chunks": [
      {
       "text": "Then the hunt moved to the seabed: unmapped undersea mountains, water up to 6 km deep.",
       "start": 16.455,
       "end": 24.507
      },
      {
       "text": "Ships towing sonar searched more than 120,000 km\u00b2.",
       "start": 24.507,
       "end": 29.639
      }
     ]
    },
    {
     "id": "s08d",
     "voice": "narrator",
     "start": 29.689,
     "end": 43.796,
     "sub": "In January 2017 Malaysia, Australia and China suspended the search. Australia's investigators called it \u201calmost inconceivable\u201d that a large airliner could still be missing.",
     "chunks": [
      {
       "text": "In January 2017 Malaysia, Australia and China suspended the search.",
       "start": 29.689,
       "end": 35.249
      },
      {
       "text": "Australia\u2019s investigators called it \u201calmost inconceivable\u201d that a large airliner could still be",
       "start": 35.249,
       "end": 43.132
      },
      {
       "text": "missing.",
       "start": 43.132,
       "end": 44.246
      }
     ]
    },
    {
     "id": "s08e",
     "voice": "narrator",
     "start": 44.396,
     "end": 58.692,
     "sub": "In 2018 Ocean Infinity tried again with robot submarines, on a \u201cno find, no fee\u201d basis. In four months it covered another 112,000 km\u00b2. It found nothing.",
     "chunks": [
      {
       "text": "In 2018 Ocean Infinity tried again with robot submarines, on a \u201cno find, no fee\u201d basis.",
       "start": 44.396,
       "end": 52.633
      },
      {
       "text": "In four months it covered another 112,000 km\u00b2. It found nothing.",
       "start": 52.633,
       "end": 59.292
      }
     ]
    }
   ]
  },
  "s09": {
   "title": "What the sea gave back",
   "offset": 311.867,
   "duration": 44.2,
   "segments": [
    {
     "id": "s09a",
     "voice": "narrator",
     "start": 0.6,
     "end": 3.42,
     "sub": "The ocean, though, had begun to give something back.",
     "chunks": [
      {
       "text": "The ocean, though, had begun to give something back.",
       "start": 0.6,
       "end": 3.87
      }
     ]
    },
    {
     "id": "s09b",
     "voice": "narrator",
     "start": 3.92,
     "end": 16.392,
     "sub": "In July 2015, on R\u00e9union Island, beach cleaners found a piece of wing covered in barnacles. It was a flaperon from Flight 370: the first proof it had ended in the sea.",
     "chunks": [
      {
       "text": "In July 2015, on R\u00e9union Island, beach cleaners found a piece of wing covered in barnacles.",
       "start": 3.92,
       "end": 10.757
      },
      {
       "text": "It was a flaperon from Flight 370: the first proof it had ended in the sea.",
       "start": 10.757,
       "end": 16.842
      }
     ]
    },
    {
     "id": "s09c",
     "voice": "narrator",
     "start": 16.892,
     "end": 31.048,
     "sub": "More pieces washed up in South Africa, Mozambique, Mauritius, Tanzania and Madagascar. Three are confirmed; many more are judged almost certain or highly likely.",
     "chunks": [
      {
       "text": "More pieces washed up in South Africa, Mozambique, Mauritius, Tanzania and Madagascar.",
       "start": 16.892,
       "end": 24.501
      },
      {
       "text": "Three are confirmed; many more are judged almost certain or highly likely.",
       "start": 24.501,
       "end": 31.498
      }
     ]
    },
    {
     "id": "s09d",
     "voice": "narrator",
     "start": 31.548,
     "end": 43.004,
     "sub": "Drift models run backwards from the finds pointed to the 7th arc. And the flaps appear to have been retracted, which argues against a controlled landing on water.",
     "chunks": [
      {
       "text": "Drift models run backwards from the finds pointed to the 7th arc.",
       "start": 31.548,
       "end": 36.173
      },
      {
       "text": "And the flaps appear to have been retracted, which argues against a controlled landing on water.",
       "start": 36.173,
       "end": 43.604
      }
     ]
    }
   ]
  },
  "s10": {
   "title": "The official answer",
   "offset": 356.067,
   "duration": 25.8,
   "segments": [
    {
     "id": "s10a",
     "voice": "narrator",
     "start": 0.6,
     "end": 8.333,
     "sub": "In July 2018, Malaysian investigators published their final report. They could not say why the plane disappeared.",
     "chunks": [
      {
       "text": "In July 2018, Malaysian investigators published their final report.",
       "start": 0.6,
       "end": 5.226
      },
      {
       "text": "They could not say why the plane disappeared.",
       "start": 5.226,
       "end": 8.783
      }
     ]
    },
    {
     "id": "s10b",
     "voice": "narrator",
     "start": 8.833,
     "end": 19.63,
     "sub": "The turns were most likely made under manual control. Nothing unusual was found in the pilots' backgrounds. Third-party interference could not be ruled out.",
     "chunks": [
      {
       "text": "The turns were most likely made under manual control.",
       "start": 8.833,
       "end": 12.548
      },
      {
       "text": "Nothing unusual was found in the pilots' backgrounds.",
       "start": 12.548,
       "end": 16.264
      },
      {
       "text": "Third-party interference could not be ruled out.",
       "start": 16.264,
       "end": 20.08
      }
     ]
    },
    {
     "id": "s10c",
     "voice": "narrator",
     "start": 20.13,
     "end": 24.815,
     "sub": "They also found that air traffic control had failed to follow procedures that night.",
     "chunks": [
      {
       "text": "They also found that air traffic control had failed to follow procedures that night.",
       "start": 20.13,
       "end": 25.415
      }
     ]
    }
   ]
  },
  "s11": {
   "title": "Claims and evidence",
   "offset": 381.867,
   "duration": 43.367,
   "segments": [
    {
     "id": "s11a",
     "voice": "narrator",
     "start": 0.6,
     "end": 5.433,
     "sub": "Without the wreckage, theories filled the silence. The evidence rules some of them out.",
     "chunks": [
      {
       "text": "Without the wreckage, theories filled the silence. The evidence rules some of them out.",
       "start": 0.6,
       "end": 5.883
      }
     ]
    },
    {
     "id": "s11b",
     "voice": "narrator",
     "start": 5.933,
     "end": 13.61,
     "sub": "It did not crash in the South China Sea. Radar, satellite data and the debris show it flew for hours to the south.",
     "chunks": [
      {
       "text": "It did not crash in the South China Sea.",
       "start": 5.933,
       "end": 8.651
      },
      {
       "text": "Radar, satellite data and the debris show it flew for hours to the south.",
       "start": 8.651,
       "end": 14.06
      }
     ]
    },
    {
     "id": "s11c",
     "voice": "narrator",
     "start": 14.11,
     "end": 19.616,
     "sub": "It did not land intact somewhere. The final signals point to a fast descent into the ocean.",
     "chunks": [
      {
       "text": "It did not land intact somewhere. The final signals point to a fast descent into the ocean.",
       "start": 14.11,
       "end": 20.066
      }
     ]
    },
    {
     "id": "s11d",
     "voice": "narrator",
     "start": 20.116,
     "end": 34.141,
     "sub": "A deliberate act from the cockpit remains possible. A flight into the southern Indian Ocean on the captain's home simulator fuelled suspicion, but investigators found no proof and named no one.",
     "chunks": [
      {
       "text": "A deliberate act from the cockpit remains possible.",
       "start": 20.116,
       "end": 23.861
      },
      {
       "text": "A flight into the southern Indian Ocean on the captain\u2019s home simulator fuelled suspicion,",
       "start": 23.861,
       "end": 30.47
      },
      {
       "text": "but investigators found no proof and named no one.",
       "start": 30.47,
       "end": 34.591
      }
     ]
    },
    {
     "id": "s11e",
     "voice": "narrator",
     "start": 34.641,
     "end": 42.166,
     "sub": "A hijacking, a ghost flight after a fire, new methods that claim to pinpoint the wreck: none has been proven.",
     "chunks": [
      {
       "text": "A hijacking, a ghost flight after a fire, new methods that claim to pinpoint the wreck:",
       "start": 34.641,
       "end": 40.702
      },
      {
       "text": "none has been proven.",
       "start": 40.702,
       "end": 42.766
      }
     ]
    }
   ]
  },
  "s12": {
   "title": "Still searching",
   "offset": 425.234,
   "duration": 36.433,
   "segments": [
    {
     "id": "s12a",
     "voice": "narrator",
     "start": 0.6,
     "end": 9.461,
     "sub": "In 2025 Ocean Infinity returned on the same terms: US$70 million if it finds the plane, nothing if it doesn't.",
     "chunks": [
      {
       "text": "In 2025 Ocean Infinity returned on the same terms:",
       "start": 0.6,
       "end": 4.665
      },
      {
       "text": "US$70 million if it finds the plane, nothing if it doesn\u2019t.",
       "start": 4.665,
       "end": 9.911
      }
     ]
    },
    {
     "id": "s12b",
     "voice": "narrator",
     "start": 9.961,
     "end": 17.038,
     "sub": "Across two short seasons, its robots surveyed about 7,500 km\u00b2. Again, nothing.",
     "chunks": [
      {
       "text": "Across two short seasons, its robots surveyed about 7,500 km\u00b2. Again, nothing.",
       "start": 9.961,
       "end": 17.488
      }
     ]
    },
    {
     "id": "s12c",
     "voice": "narrator",
     "start": 17.538,
     "end": 27.022,
     "sub": "Malaysia has extended the contract to June 2027, to search the last 7,400 km\u00b2 of the target area.",
     "chunks": [
      {
       "text": "Malaysia has extended the contract to June 2027,",
       "start": 17.538,
       "end": 22.28
      },
      {
       "text": "to search the last 7,400 km\u00b2 of the target area.",
       "start": 22.28,
       "end": 27.472
      }
     ]
    },
    {
     "id": "s12d",
     "voice": "narrator",
     "start": 27.522,
     "end": 35.234,
     "sub": "The families are still waiting. Some have taken the airline to court. Many have spent twelve years asking governments to keep looking.",
     "chunks": [
      {
       "text": "The families are still waiting. Some have taken the airline to court.",
       "start": 27.522,
       "end": 31.523
      },
      {
       "text": "Many have spent twelve years asking governments to keep looking.",
       "start": 31.523,
       "end": 35.834
      }
     ]
    }
   ]
  },
  "s13": {
   "title": "Epilogue",
   "offset": 461.667,
   "duration": 21.233,
   "segments": [
    {
     "id": "s13a",
     "voice": "narrator",
     "start": 0.8,
     "end": 10.574,
     "sub": "Somewhere along a curved line in the southern Indian Ocean, several kilometres down, lies a Boeing 777 and the answer to what happened on board.",
     "chunks": [
      {
       "text": "Somewhere along a curved line in the southern Indian Ocean,",
       "start": 0.8,
       "end": 4.833
      },
      {
       "text": "several kilometres down, lies a Boeing 777 and the answer to what happened on board.",
       "start": 4.833,
       "end": 11.024
      }
     ]
    },
    {
     "id": "s13b",
     "voice": "narrator",
     "start": 11.374,
     "end": 15.244,
     "sub": "Until it is found, 239 people remain missing.",
     "chunks": [
      {
       "text": "Until it is found, 239 people remain missing.",
       "start": 11.374,
       "end": 15.844
      }
     ]
    }
   ]
  }
 },
 "total": 482.9
};
