"""Turn cues.json into scenes/timing.js in the format scenes/lib.js expects (no captions)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FPS = 30
c = json.loads((ROOT / "cues.json").read_text())
timing = {"fps": FPS, "order": [], "scenes": {}}
offset = 0.0
for sid, s in c["scenes"].items():
    dur = round(round((s["to"] - s["from"]) * FPS) / FPS, 3)
    segs = [{"id": k, "start": round(v - s["from"], 3), "end": round(v - s["from"], 3), "sub": "", "chunks": []}
            for k, v in sorted(s["cues"].items(), key=lambda kv: kv[1])]
    timing["order"].append(sid)
    timing["scenes"][sid] = {"title": sid, "offset": round(offset, 3), "duration": dur, "segments": segs}
    offset += dur
timing["total"] = round(offset, 3)
(ROOT / "scenes" / "timing.js").write_text("// Generated by tools/make_timing.py from cues.json. Do not edit.\nwindow.TIMING = " + json.dumps(timing, indent=1) + ";\n")
for sid in timing["order"]:
    print(sid, timing["scenes"][sid]["duration"])
