// Generated by tools/make_timing.py from cues.json. Do not edit.
window.TIMING = {
 "fps": 30,
 "order": [
  "rA",
  "rB"
 ],
 "scenes": {
  "rA": {
   "title": "rA",
   "offset": 0.0,
   "duration": 174.7,
   "segments": [
    {
     "id": "midnight",
     "start": 2.1,
     "end": 2.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "klia",
     "start": 9.2,
     "end": 9.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "beijing",
     "start": 11.7,
     "end": 11.7,
     "sub": "",
     "chunks": []
    },
    {
     "id": "boeing",
     "start": 15.5,
     "end": 15.5,
     "sub": "",
     "chunks": []
    },
    {
     "id": "safest",
     "start": 19.4,
     "end": 19.4,
     "sub": "",
     "chunks": []
    },
    {
     "id": "onboard",
     "start": 23.7,
     "end": 23.7,
     "sub": "",
     "chunks": []
    },
    {
     "id": "pax",
     "start": 24.6,
     "end": 24.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "crew",
     "start": 27.0,
     "end": 27.0,
     "sub": "",
     "chunks": []
    },
    {
     "id": "nationalities",
     "start": 29.3,
     "end": 29.3,
     "sub": "",
     "chunks": []
    },
    {
     "id": "families",
     "start": 31.2,
     "end": 31.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "calligraphy",
     "start": 34.3,
     "end": 34.3,
     "sub": "",
     "chunks": []
    },
    {
     "id": "cabin",
     "start": 37.9,
     "end": 37.9,
     "sub": "",
     "chunks": []
    },
    {
     "id": "lights",
     "start": 39.8,
     "end": 39.8,
     "sub": "",
     "chunks": []
    },
    {
     "id": "redeye",
     "start": 42.6,
     "end": 42.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "scs",
     "start": 45.1,
     "end": 45.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "sleep",
     "start": 47.1,
     "end": 47.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "cruise",
     "start": 52.8,
     "end": 52.8,
     "sub": "",
     "chunks": []
    },
    {
     "id": "fl350",
     "start": 55.1,
     "end": 55.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "acars107",
     "start": 57.4,
     "end": 57.4,
     "sub": "",
     "chunks": []
    },
    {
     "id": "update",
     "start": 60.5,
     "end": 60.5,
     "sub": "",
     "chunks": []
    },
    {
     "id": "acars",
     "start": 64.8,
     "end": 64.8,
     "sub": "",
     "chunks": []
    },
    {
     "id": "standard",
     "start": 72.0,
     "end": 72.0,
     "sub": "",
     "chunks": []
    },
    {
     "id": "altitude",
     "start": 75.2,
     "end": 75.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "tolerances",
     "start": 77.2,
     "end": 77.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "twelvemin",
     "start": 79.5,
     "end": 79.5,
     "sub": "",
     "chunks": []
    },
    {
     "id": "igari",
     "start": 82.1,
     "end": 82.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "boundary",
     "start": 84.6,
     "end": 84.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "handoff",
     "start": 88.3,
     "end": 88.3,
     "sub": "",
     "chunks": []
    },
    {
     "id": "atc",
     "start": 91.6,
     "end": 91.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "atcEnd",
     "start": 99.2,
     "end": 99.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "cockpit",
     "start": 100.5,
     "end": 100.5,
     "sub": "",
     "chunks": []
    },
    {
     "id": "reply",
     "start": 103.2,
     "end": 103.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "replyEnd",
     "start": 105.2,
     "end": 105.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "signoff",
     "start": 106.9,
     "end": 106.9,
     "sub": "",
     "chunks": []
    },
    {
     "id": "nohint",
     "start": 109.2,
     "end": 109.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "lastcomm",
     "start": 112.7,
     "end": 112.7,
     "sub": "",
     "chunks": []
    },
    {
     "id": "moments",
     "start": 117.3,
     "end": 117.3,
     "sub": "",
     "chunks": []
    },
    {
     "id": "gap",
     "start": 119.5,
     "end": 119.5,
     "sub": "",
     "chunks": []
    },
    {
     "id": "t121",
     "start": 124.9,
     "end": 124.9,
     "sub": "",
     "chunks": []
    },
    {
     "id": "xpdr",
     "start": 127.5,
     "end": 127.5,
     "sub": "",
     "chunks": []
    },
    {
     "id": "ceases",
     "start": 129.1,
     "end": 129.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "secondary",
     "start": 130.3,
     "end": 130.3,
     "sub": "",
     "chunks": []
    },
    {
     "id": "wipes",
     "start": 132.8,
     "end": 132.8,
     "sub": "",
     "chunks": []
    },
    {
     "id": "civilian",
     "start": 135.7,
     "end": 135.7,
     "sub": "",
     "chunks": []
    },
    {
     "id": "vanish",
     "start": 140.8,
     "end": 140.8,
     "sub": "",
     "chunks": []
    },
    {
     "id": "thinair",
     "start": 143.9,
     "end": 143.9,
     "sub": "",
     "chunks": []
    },
    {
     "id": "military",
     "start": 144.7,
     "end": 144.7,
     "sub": "",
     "chunks": []
    },
    {
     "id": "chilling",
     "start": 148.7,
     "end": 148.7,
     "sub": "",
     "chunks": []
    },
    {
     "id": "notcrashed",
     "start": 150.6,
     "end": 150.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "leftbank",
     "start": 153.5,
     "end": 153.5,
     "sub": "",
     "chunks": []
    },
    {
     "id": "abandon",
     "start": 157.0,
     "end": 157.0,
     "sub": "",
     "chunks": []
    },
    {
     "id": "turnback",
     "start": 160.8,
     "end": 160.8,
     "sub": "",
     "chunks": []
    },
    {
     "id": "flies",
     "start": 164.0,
     "end": 164.0,
     "sub": "",
     "chunks": []
    },
    {
     "id": "sumatra",
     "start": 166.1,
     "end": 166.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "south",
     "start": 168.3,
     "end": 168.3,
     "sub": "",
     "chunks": []
    },
    {
     "id": "ocean",
     "start": 169.3,
     "end": 169.3,
     "sub": "",
     "chunks": []
    }
   ]
  },
  "rB": {
   "title": "rB",
   "offset": 174.7,
   "duration": 55.8,
   "segments": [
    {
     "id": "turning",
     "start": 0.1,
     "end": 0.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "questions",
     "start": 3.6,
     "end": 3.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "q1",
     "start": 6.8,
     "end": 6.8,
     "sub": "",
     "chunks": []
    },
    {
     "id": "q1b",
     "start": 9.9,
     "end": 9.9,
     "sub": "",
     "chunks": []
    },
    {
     "id": "q2",
     "start": 13.7,
     "end": 13.7,
     "sub": "",
     "chunks": []
    },
    {
     "id": "zigzag",
     "start": 17.1,
     "end": 17.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "decomp",
     "start": 22.2,
     "end": 22.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "battery",
     "start": 25.2,
     "end": 25.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "cyber",
     "start": 28.0,
     "end": 28.0,
     "sub": "",
     "chunks": []
    },
    {
     "id": "deliberate",
     "start": 30.6,
     "end": 30.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "aboveall",
     "start": 35.2,
     "end": 35.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "how",
     "start": 36.2,
     "end": 36.2,
     "sub": "",
     "chunks": []
    },
    {
     "id": "souls",
     "start": 39.1,
     "end": 39.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "beacon",
     "start": 41.4,
     "end": 41.4,
     "sub": "",
     "chunks": []
    },
    {
     "id": "pings",
     "start": 44.1,
     "end": 44.1,
     "sub": "",
     "chunks": []
    },
    {
     "id": "greatest",
     "start": 47.4,
     "end": 47.4,
     "sub": "",
     "chunks": []
    },
    {
     "id": "century",
     "start": 50.6,
     "end": 50.6,
     "sub": "",
     "chunks": []
    },
    {
     "id": "end",
     "start": 51.5,
     "end": 51.5,
     "sub": "",
     "chunks": []
    }
   ]
  }
 },
 "total": 230.5
};
